/*   Copyright (C) 2013-2014 Computer Sciences Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License. */

/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package ezbake.services.deploy.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class CustomServiceInfo implements org.apache.thrift.TBase<CustomServiceInfo, CustomServiceInfo._Fields>, java.io.Serializable, Cloneable, Comparable<CustomServiceInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CustomServiceInfo");

  private static final org.apache.thrift.protocol.TField CONTROL_SCRIPTS_FIELD_DESC = new org.apache.thrift.protocol.TField("controlScripts", org.apache.thrift.protocol.TType.STRUCT, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new CustomServiceInfoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new CustomServiceInfoTupleSchemeFactory());
  }

  public ControlScripts controlScripts; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CONTROL_SCRIPTS((short)1, "controlScripts");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CONTROL_SCRIPTS
          return CONTROL_SCRIPTS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private _Fields optionals[] = {_Fields.CONTROL_SCRIPTS};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CONTROL_SCRIPTS, new org.apache.thrift.meta_data.FieldMetaData("controlScripts", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ControlScripts.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CustomServiceInfo.class, metaDataMap);
  }

  public CustomServiceInfo() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CustomServiceInfo(CustomServiceInfo other) {
    if (other.isSetControlScripts()) {
      this.controlScripts = new ControlScripts(other.controlScripts);
    }
  }

  public CustomServiceInfo deepCopy() {
    return new CustomServiceInfo(this);
  }

  @Override
  public void clear() {
    this.controlScripts = null;
  }

  public ControlScripts getControlScripts() {
    return this.controlScripts;
  }

  public CustomServiceInfo setControlScripts(ControlScripts controlScripts) {
    this.controlScripts = controlScripts;
    return this;
  }

  public void unsetControlScripts() {
    this.controlScripts = null;
  }

  /** Returns true if field controlScripts is set (has been assigned a value) and false otherwise */
  public boolean isSetControlScripts() {
    return this.controlScripts != null;
  }

  public void setControlScriptsIsSet(boolean value) {
    if (!value) {
      this.controlScripts = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case CONTROL_SCRIPTS:
      if (value == null) {
        unsetControlScripts();
      } else {
        setControlScripts((ControlScripts)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case CONTROL_SCRIPTS:
      return getControlScripts();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case CONTROL_SCRIPTS:
      return isSetControlScripts();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof CustomServiceInfo)
      return this.equals((CustomServiceInfo)that);
    return false;
  }

  public boolean equals(CustomServiceInfo that) {
    if (that == null)
      return false;

    boolean this_present_controlScripts = true && this.isSetControlScripts();
    boolean that_present_controlScripts = true && that.isSetControlScripts();
    if (this_present_controlScripts || that_present_controlScripts) {
      if (!(this_present_controlScripts && that_present_controlScripts))
        return false;
      if (!this.controlScripts.equals(that.controlScripts))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(CustomServiceInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetControlScripts()).compareTo(other.isSetControlScripts());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetControlScripts()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.controlScripts, other.controlScripts);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("CustomServiceInfo(");
    boolean first = true;

    if (isSetControlScripts()) {
      sb.append("controlScripts:");
      if (this.controlScripts == null) {
        sb.append("null");
      } else {
        sb.append(this.controlScripts);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (controlScripts != null) {
      controlScripts.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CustomServiceInfoStandardSchemeFactory implements SchemeFactory {
    public CustomServiceInfoStandardScheme getScheme() {
      return new CustomServiceInfoStandardScheme();
    }
  }

  private static class CustomServiceInfoStandardScheme extends StandardScheme<CustomServiceInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CustomServiceInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CONTROL_SCRIPTS
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.controlScripts = new ControlScripts();
              struct.controlScripts.read(iprot);
              struct.setControlScriptsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CustomServiceInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.controlScripts != null) {
        if (struct.isSetControlScripts()) {
          oprot.writeFieldBegin(CONTROL_SCRIPTS_FIELD_DESC);
          struct.controlScripts.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CustomServiceInfoTupleSchemeFactory implements SchemeFactory {
    public CustomServiceInfoTupleScheme getScheme() {
      return new CustomServiceInfoTupleScheme();
    }
  }

  private static class CustomServiceInfoTupleScheme extends TupleScheme<CustomServiceInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CustomServiceInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetControlScripts()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetControlScripts()) {
        struct.controlScripts.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CustomServiceInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.controlScripts = new ControlScripts();
        struct.controlScripts.read(iprot);
        struct.setControlScriptsIsSet(true);
      }
    }
  }

}

